AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Guardfile'
  Exclude:
    - bin/*
    - script/*
    - db/migrate/*.rb
    - db/schema.rb

# Remove when upgrading to Rails 4.x
Rails/ActionFilter:
  Enabled: false

Delegate:
  Enabled: false

LineLength:
  Max: 120

Documentation:
  Enabled: false

FileName:
  Exclude:
    - Guardfile
    - Gemfile
    - Gemfile.lock
