language: ruby
env: DB=postgres
branches:
  only:
    - 'master'
rvm: 2.0.0
script: "bundle exec rake db:drop db:create db:migrate test"
before_script:
  - "cp config/database.travisci.yml config/database.yml"
  - "psql -c 'create database chicagoiands_test;' -U postgres >/dev/null"
