rvm: 1.9.2
env: DB=postgres
script: "bundle exec rake db:drop db:create db:migrate spec"
before_script:
  - "cp config/database.travisci.yml config/database.yml"
  - "psql -c 'create database chicagoiands_test;' -U postgres >/dev/null"