development:
  adapter: postgresql
  encoding: unicode
  database: chicagoiands-devel
  username: docwhat
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: chicagoiands-test
  username: docwhat
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: chicagoiands
  username: docwhat
  pool: 5
